### ISSUE TITLE
zmradio crashed on fedora 23 x86-64

### ISSUE THREAD

**Issue by kuh3h3** [timxx/xmradio#42]
compile,run ok
but if click combo box to change skin, it crash

[reandr@kuh3h3 reandr] $ gdb xmradio
Reading symbols from xmradio...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/xmradio 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.22-11.fc23.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffdde9b700 (LWP 18442)]
[New Thread 0x7fffdd69a700 (LWP 18443)]
[New Thread 0x7fffd5d75700 (LWP 18444)]
[New Thread 0x7fffd5574700 (LWP 18445)]
[New Thread 0x7fffc3ffd700 (LWP 18446)]
[New Thread 0x7fffc37fc700 (LWP 18447)]
[New Thread 0x7fffc2ffb700 (LWP 18449)]
[Thread 0x7fffc2ffb700 (LWP 18449) exited]
[New Thread 0x7fffc2ffb700 (LWP 18451)]
[New Thread 0x7fffc1691700 (LWP 18452)]
[New Thread 0x7fffc0e90700 (LWP 18454)]
[New Thread 0x7fffc0b87700 (LWP 18455)]
Detaching after fork from child process 18456.
[Thread 0x7fffc0b87700 (LWP 18455) exited]
[Thread 0x7fffc1691700 (LWP 18452) exited]
[New Thread 0x7fffc017d700 (LWP 18458)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3c9b0b6 in gdk_pixbuf_get_width () from /lib64/libgdk_pixbuf-2.0.so.0
Missing separate debuginfos, use: dnf debuginfo-install GConf2-3.2.6-15.fc23.x86_64 a52dec-0.7.4-19.fc23.x86_64 alsa-lib-1.1.1-1.fc23.x86_64 at-spi2-atk-2.18.1-1.fc23.x86_64 at-spi2-core-2.18.3-1.fc23.x86_64 atk-2.18.0-1.fc23.x86_64 bzip2-libs-1.0.6-19.fc23.x86_64 cairo-infinality-ultimate-1.14.6-1.fc23.x86_64 cairo-infinality-ultimate-gobject-1.14.6-1.fc23.x86_64 cyrus-sasl-lib-2.1.26-25.2.fc23.x86_64 dbus-glib-0.106-1.fc23.x86_64 dbus-libs-1.10.8-1.fc23.x86_64 dconf-0.24.0-2.fc23.x86_64 elfutils-libelf-0.165-2.fc23.x86_64 elfutils-libs-0.165-2.fc23.x86_64 expat-2.1.0-12.fc23.x86_64 faad2-libs-2.7-6.fc22.x86_64 ffmpeg-libs-2.8.6-1.fc23.x86_64 flac-libs-1.3.1-5.fc23.x86_64 fontconfig-infinality-ultimate-2.11.94-4.fc23.x86_64 freetype-infinality-ultimate-2.6.3-1.fc23.x86_64 fribidi-0.19.6-5.fc23.x86_64 gdk-pixbuf2-2.32.3-1.fc23.x86_64 gdk-pixbuf2-modules-2.32.3-1.fc23.x86_64 glib-networking-2.46.1-1.fc23.x86_64 glib2-2.46.2-1.fc23.x86_64 gmp-6.0.0-12.fc23.x86_64 gnutls-3.4.10-1.fc23.x86_64 gobject-introspection-1.46.0-1.fc23.x86_64 graphite2-1.3.6-1.fc23.x86_64 gsm-1.0.13-13.fc23.x86_64 gtk3-3.18.9-1.fc23.x86_64 gvfs-client-1.26.3-1.fc23.x86_64 harfbuzz-1.0.6-1.fc23.x86_64 ibus-gtk3-1.5.11-1.fc23.x86_64 ibus-libs-1.5.11-1.fc23.x86_64 json-c-0.12-6.fc23.x86_64 keyutils-libs-1.5.9-7.fc23.x86_64 krb5-libs-1.14.1-3.fc23.x86_64 lame-libs-3.99.5-5.fc23.x86_64 libICE-1.0.9-3.fc23.x86_64 libSM-1.2.2-3.fc23.x86_64 libX11-1.6.3-2.fc23.x86_64 libXau-1.0.8-5.fc23.x86_64 libXcomposite-0.4.4-7.fc23.x86_64 libXcursor-1.1.14-4.fc23.x86_64 libXdamage-1.1.4-7.fc23.x86_64 libXext-1.3.3-3.fc23.x86_64 libXfixes-5.0.1-5.fc23.x86_64 libXi-1.7.6-1.fc23.x86_64 libXinerama-1.1.3-5.fc23.x86_64 libXrandr-1.5.0-2.fc23.x86_64 libXrender-0.9.9-2.fc23.x86_64 libXtst-1.2.2-5.fc23.x86_64 libass-0.13.1-1.fc23.x86_64 libasyncns-0.8-9.fc23.x86_64 libattr-2.4.47-14.fc23.x86_64 libcap-2.24-8.fc23.x86_64 libcom_err-1.42.13-3.fc23.x86_64 libcroco-0.6.8-7.fc23.x86_64 libcurl-7.43.0-6.fc23.x86_64 libdatrie-0.2.8-6.fc23.x86_64 libdca-0.0.5-9.fc22.x86_64 libepoxy-1.2-4.fc23.x86_64 libffi-3.1-8.fc23.x86_64 libgcc-5.3.1-2.fc23.x86_64 libgcrypt-1.6.4-1.fc23.x86_64 libgomp-5.3.1-2.fc23.x86_64 libgpg-error-1.21-1.fc23.x86_64 libidn-1.32-1.fc23.x86_64 libjpeg-turbo-1.4.1-2.fc23.x86_64 libmad-0.15.1b-17.fc23.x86_64 libmodman-2.0.1-11.fc23.x86_64 libnghttp2-1.7.1-1.fc23.x86_64 libogg-1.3.2-4.fc23.x86_64 libpeas-1.16.0-1.fc23.x86_64 libproxy-0.4.11-12.fc23.x86_64 librsvg2-2.40.13-1.fc23.x86_64 libsamplerate-0.1.8-9.fc23.x86_64 libselinux-2.4-4.fc23.x86_64 libsndfile-1.0.25-18.fc23.x86_64 libssh2-1.6.0-4.fc23.x86_64 libstdc++-5.3.1-2.fc23.x86_64 libtasn1-4.5-2.fc23.x86_64 libthai-0.1.21-2.fc23.x86_64 libtheora-1.1.1-13.fc23.x86_64 libuuid-2.27.1-2.fc23.x86_64 libva-1.6.2-2.fc23.x86_64 libvorbis-1.3.4-5.fc23.x86_64 libvpx-1.4.0-6.fc23.x86_64 libwayland-client-1.9.0-1.fc23.x86_64 libwayland-cursor-1.9.0-1.fc23.x86_64 libxcb-1.11.1-1.fc23.x86_64 libxkbcommon-0.5.0-2.fc23.x86_64 libxml2-2.9.3-2.fc23.x86_64 lua-5.3.2-2.fc23.x86_64 mesa-libwayland-egl-11.1.0-2.20151218.fc23.x86_64 minizip-1.2.8-9.fc23.x86_64 nettle-3.2-1.fc23.x86_64 nspr-4.12.0-1.fc23.x86_64 nss-3.23.0-1.0.fc23.x86_64 nss-mdns-0.10-16.fc23.x86_64 nss-softokn-freebl-3.23.0-1.0.fc23.x86_64 nss-util-3.23.0-1.0.fc23.x86_64 openjpeg-libs-1.5.1-15.fc23.x86_64 openldap-2.4.40-14.fc23.x86_64 openssl-libs-1.0.2g-2.fc23.x86_64 opus-1.1.2-1.fc23.x86_64 orc-0.4.25-1.fc23.x86_64 p11-kit-0.23.2-1.fc23.x86_64 pango-1.38.1-1.fc23.x86_64 pcre-8.38-7.fc23.x86_64 pixman-0.34.0-1.fc23.x86_64 pulseaudio-libs-7.1-1.fc23.x86_64 schroedinger-1.0.11-9.fc23.x86_64 soxr-0.1.2-1.fc23.x86_64 speex-1.2-0.24.rc2.fc23.x86_64 systemd-libs-222-14.fc23.x86_64 taglib-1.10-1.fc23.x86_64 tcp_wrappers-libs-7.6-81.fc23.x86_64 vlc-2.2.2-1.fc23.x86_64 vlc-core-2.2.2-1.fc23.x86_64 x264-libs-0.148-5.20160118git5c65704.fc23.x86_64 x265-libs-1.8-1.fc23.x86_64 xvidcore-1.3.4-2.fc23.x86_64 xz-libs-5.2.1-3.fc23.x86_64 zlib-1.2.8-9.fc23.x86_64
(gdb) bt full
#0  0x00007ffff3c9b0b6 in gdk_pixbuf_get_width () at /lib64/libgdk_pixbuf-2.0.so.0
#1  0x00007ffff7bca5e3 in set_cover_image () at /lib64/libxmradio-core.so
#2  0x00007ffff7bcb39d in set_skin.isra () at /lib64/libxmradio-core.so
#3  0x00007ffff7bcd27b in on_combo_box_changed () at /lib64/libxmradio-core.so
#4  0x00007ffff3a509d4 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#5  0x00007ffff3a6b2bd in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#6  0x00007ffff3a6b8ff in g_signal_emit () at /lib64/libgobject-2.0.so.0
#7  0x00007ffff63afa3b in gtk_combo_box_set_active_internal () at /lib64/libgtk-3.so.0
#8  0x00007ffff63b2118 in gtk_combo_box_set_active_iter () at /lib64/libgtk-3.so.0
#9  0x00007ffff63b3680 in gtk_combo_box_set_active_id () at /lib64/libgtk-3.so.0
#10 0x00007ffff3a507a5 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#11 0x00007ffff3a62851 in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#12 0x00007ffff3a6b530 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#13 0x00007ffff3a6b8ff in g_signal_emit () at /lib64/libgobject-2.0.so.0
#14 0x00007ffff65b294e in gtk_widget_activate () at /lib64/libgtk-3.so.0
#15 0x00007ffff64904f6 in gtk_menu_shell_activate_item () at /lib64/libgtk-3.so.0
#16 0x00007ffff6490824 in gtk_menu_shell_button_release () at /lib64/libgtk-3.so.0
#17 0x00007ffff6472fda in _gtk_marshal_BOOLEAN__BOXEDv () at /lib64/libgtk-3.so.0
#18 0x00007ffff3a509d4 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#19 0x00007ffff3a6add3 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#20 0x00007ffff3a6b8ff in g_signal_emit () at /lib64/libgobject-2.0.so.0
#21 0x00007ffff65b04bc in gtk_widget_event_internal () at /lib64/libgtk-3.so.0
#22 0x00007ffff647034e in propagate_event () at /lib64/libgtk-3.so.0
#23 0x00007ffff64720fc in gtk_main_do_event () at /lib64/libgtk-3.so.0
#24 0x00007ffff5feae92 in gdk_event_source_dispatch () at /lib64/libgdk-3.so.0
#25 0x00007ffff3751e3a in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#26 0x00007ffff37521d0 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#27 0x00007ffff375227c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#28 0x00007ffff510aa0c in g_application_run () at /lib64/libgio-2.0.so.0
#29 0x00000000004019fc in main ()
(gdb) i r
rax            0x6b21d0	7021008
rbx            0xe1b800	14792704
rcx            0x0	0
rdx            0x1	1
rsi            0xe1b800	14792704
rdi            0xe1b800	14792704
rbp            0x8828c0	0x8828c0
rsp            0x7fffffffc920	0x7fffffffc920
r8             0xd7f3b0	14152624
r9             0x1	1
r10            0x36a0	13984
r11            0x33	51
r12            0x3c	60
r13            0x55	85
r14            0x7fffffffc9a8	140737488341416
r15            0x882970	8923504
rip            0x7ffff3c9b0b6	0x7ffff3c9b0b6 <gdk_pixbuf_get_width+22>
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) q
A debugging session is active.

**Comment by kuh3h3** [comment]
maybe  this is multi-lib enviroment problem.
so i built xmradio with this command options.
after that , copied /usr/lib-installed files to /usr/lib64.

cmake -DCMAKE_INSTALL_PREFIX/usr -DCMAKE_INSTALL_LIBDIR=lib64 ..

**Comment by timxx** [comment]
What desktop you use? I tried kde, seems it works. -DCMAKE_INSTALL_LIBDIR=lib64 not works for me, I need copy those libs from /usr/lib to /usr/lib64 manully. :(

**Comment by timxx** [comment]
Would you mind compile again using the latest source code. I just tested on lxde-desktop, no crahes..
If you still have the problem, please send me the core dump file. Thanks.

**Comment by kuh3h3** [comment]
ok  , after  rm -rf , clean rebuild. no segfaults. works well.
But can`t login to private radio studio.
Always  says "Login failed .No such email".

my xiami id have not email address.
it works but xmradio cant not login to there.
http://www.xiami.com/radio/play/type/4/oid/140961756?spm=a1z1s.6626009.0.0.DEh9zK

**Comment by timxx** [comment]
Sorry, it might not support other account login in current login method. I'll find the way supports the other accounts later.
